---
- name: Clone ICVPN meta repository
  git:
    repo: "{{ icvpn_meta_git_root }}"
    dest: "/opt/icvpn-meta/"
    version: "{{ icvpn_meta_git_commit }}"

- name: Clone ICVPN scripts repository
  git:
    repo: "{{ icvpn_scripts_git_root }}"
    dest: "/opt/icvpn-scripts/"
    version: "{{ icvpn_scripts_git_commit }}"

- name: Install cronjob to automatically update bgp bird configurations
  template:
    src: icvpn-update
    dest: /etc/cron.hourly/icvpn-update
    mode: 0755
    owner: root
    group: root

- name: Install config templates
  template:
    src: "{{ item }}"
    dest: "/etc/bird/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
  - bird.conf
  - bird6.conf
  notify:
  - reload bird
  - reload bird6

- name: Install internal ipv4 config templates
  template:
    src: bgptunnelv4.j2
    dest: /etc/bird/bird.conf.d/90_tunnel_ebgp.conf
    mode: 0644
    owner: root
    group: root
  notify:
  - reload bird

- name: Install internal ipv6 config templates
  template:
    src: bgptunnelv6.j2
    dest: /etc/bird/bird6.conf.d/90_tunnel_ebgp.conf
    mode: 0644
    owner: root
    group: root
  notify:
  - reload bird6

- name: Install icvpn prefix file generation script
  template:
    src: gen_icvpn_pfx_file.sh
    dest: /tmp/gen_icvpn_pfx_file.sh
    mode: 0755
    owner: root
    group: root

- name: Generate initial icvpn prefix file
  ansible.builtin.shell: /tmp/gen_icvpn_pfx_file.sh
