---
- name: Install smokeping packages
  apt:
    name: ['smokeping', 'curl', 'libauthen-radius-perl', 'libnet-ldap-perl', 'libnet-dns-perl', 'libio-socket-ssl-perl', 'libnet-telnet-perl', 'libsocket6-perl', 'libio-socket-inet6-perl', 'apache2']
    state: present
    update_cache: yes
    cache_valid_time: 1800

- name: Install sSMTP as /usr/sbin/sendmail if missing
  shell: |
    set -o pipefail
    /usr/bin/test -e /usr/sbin/sendmail || apt -y install ssmtp
  args:
    executable: bash
  changed_when: False
  failed_when: False
  check_mode: no

- name: Configure smokeping General
  template: src=General.j2 dest=/etc/smokeping/config.d/General mode=0644
  notify: restart smokeping

- name: Configure smokeping Targets
  template: src=Targets.j2 dest=/etc/smokeping/config.d/Targets mode=0644
  with_items: smokeping_targets
  notify: restart smokeping

- name: Configure smokeping FPing probes
  template: src=Probes.j2 dest=/etc/smokeping/config.d/Probes mode=0644
  notify: restart smokeping

- name: Enable Apache CGI module
  apache2_module: state=present name=cgid

- name: Configure Apache virtualhost for smokeping
  template: src=smokeping.conf.j2 dest=/etc/apache2/sites-available/smokeping.conf

#- name: Enable smokeping Apache virtualhosts
#  command: /usr/sbin/a2ensite smokeping.conf creates=/etc/apache2/conf-enabled/smokeping.conf
#  notify: restart apache

- name: Create directory
  file: path=/var/run/smokeping state=directory owner=smokeping group=smokeping

