#!/bin/bash

logger "$0: args .$1. .$2. .$3. .$4. .$5. .$6. .$7. .$8. .$9."
ssh -o StrictHostKeyChecking=no -i /var/lib/nagios/.ssh/id_rsa nrpe@192.251.226.118 "/usr/lib/nagios/plugins/check_nrpe $1 $2 $3 $4 $5 $6 $7 $8 $9"
