---
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking

- name: Check for /etc/network/interfaces.d
  stat:
    path: /etc/network/interfaces.d
  register: interfaces_d

- name: Creates /etc/network/interfaces.d directory if missing
  file:
    path: /etc/network/interfaces.d
    state: directory
    owner: root
    group: root
    mode: 0775
    when: interfaces_d.stat.exists == false

- name: Konfig für die lo-Schnittstelle
  template: src="lo.j2" dest="/etc/network/interfaces.d/00_lo.cfg"
  notify:
    - restart networking

- name: lo-Block aus interfaces entfernen
  lineinfile: dest="/etc/network/interfaces" line="auto lo" state="absent"

- name: lo-Block aus interfaces entfernen
  lineinfile: dest="/etc/network/interfaces" line="iface lo inet loopback" state="absent"

- name: Create interfaces - gretap to ffrl or ffnw
  template: src="gre_upstream.j2" dest="/etc/network/interfaces.d/40_gre_upstream.cfg"
  notify:
    - restart networking
  when: ffrl_tun is defined or ffnw_tun is defined or ffgt_tun is defined

