- name: Install dependencies for this role
  apt:
    pkg: ['linux-modules-extra-{{ansible_kernel}}']
  when: ansible_distribution == 'Ubuntu'

- name: Install dependencies for this role
  apt:
    pkg: ['python', 'ifupdown', 'libelf-dev', 'aptitude', 'python-pip']
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04') or
        (ansible_distribution == 'Debian' and ansible_distribution_version == '10')

- name: Install dependencies for this role
  apt:
    pkg: ['python', 'ifupdown', 'libelf-dev', 'aptitude', 'python3-pip']
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04') or
        (ansible_distribution == 'Debian' and ansible_distribution_version == '11')
