---
- name: Stop gateways_yanic_respondd's respondd service
  service:
    name: respondd
    state: stopped
  ignore_errors: true

- name: Disable gateways_yanic_respondd's respondd service
  service:
    name: respondd
    enabled: no
  ignore_errors: true

- name: Remove gateways_yanic_respondd's binary
  ansible.builtin.file:
    path: /usr/local/bin/yanic
    state: absent

- name: Remove gateways_yanic_respondd's systemd unit
  ansible.builtin.file:
    path: /lib/systemd/system/respondd.service
    state: absent
  notify: systemctl reload

- name: Remove gateways_yanic_respondd's config file
  ansible.builtin.file:
    path: /etc/respondd.conf
    state: absent

- name: Install dependencies
  apt:
    pkg: ['python3', 'ethtool', 'lsb-release' ]
    state: present

- name: Clone mesh-announce repo
  git:
    repo: https://github.com/ffnord/mesh-announce.git
    dest: /opt/mesh-announce
    clone: yes
    update: yes
    force: yes
  notify: restart respondd

- name: create configuration
  template:
    src: respondd.conf.j2
    dest: /opt/mesh-announce/respondd.conf
  notify: restart respondd

- name: create systemd file
  template:
    src: respondd.service.j2
    dest: /etc/systemd/system/respondd.service
  notify: systemctl reload

- name: enable respondd
  systemd:
    name: respondd
    enabled: yes
    masked: no
  notify: systemctl reload
