---
# Tasks for getap network interfaces

- name: Create interfaces - inter_gre file
  template: src="gretap.j2" dest="/etc/network/interfaces.d/30_gretap.cfg"
  notify:
    - restart networking
  when: domaenenliste is defined

- name: Create interfaces - inter_gre file
  template: src="dot_gretap.j2" dest="/root/gretap.dot"
  when: domaenenliste is defined

- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*.cfg"
  notify:
    - restart networking
  when: domaenenliste is defined
