---
- name: Install required packages
  apt:
    pkg: ['apt', 'git']
    update_cache: yes
    state: present

- name: Add nodejs repo keys
  apt_key:
    id: 1655A0AB68576280
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Add yarn repo keys
  apt_key:
    id: 23E7166788B63E1E
    url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    state: present

- name: Add repo for yarn
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"

- name: Add repo for yarn
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://dl.yarnpkg.com/debian/ stable main "

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present

- name: Install yarn
  apt:
    pkg: yarn
    state: present

- name: Clone repository
  git:
    repo: "{{ meshviewer_git_root }}"
    dest: "{{ meshviewer_path_src }}/"
    version: "{{ meshviewer_git_version }}"
    force: yes

- name: Install node dependencies
  command: yarn install
  args:
    chdir: "{{ meshviewer_path_src }}"

- name: Build meshviewer
  command: node_modules/.bin/gulp
  args:
    chdir: "{{ meshviewer_path_src }}"

- name: Create destination directory
  file:
    path="{{ meshviewer_path_bin }}"
    state=directory

- name: Install rsync
  apt:
    name: rsync

# does not work (https://github.com/ansible/ansible/issues/11873)
#- name: Copy generated files
#  delegate_to: "{{ inventory_hostname }}"
#  synchronize:
#    src: {{ meshviewer_path_src }}/build/
#    dest: {{ meshviewer_path_bin }}/
#    delete: True
#    rsync_opts:
#    - "--exclude=config.json"

- name: Copy files
  command: >
    rsync -a --delete
    {{ meshviewer_path_src }}/build/
    {{ meshviewer_path_bin }}/

- name: Enable Apache
  include: apache.yml
  when: meshviewer_apache

- name: Enable Geojson
  import_tasks: geojson.yml
  when: meshviewer_geojson
