---
- name: Install NRPE-Server
  package:
    name: nagios-nrpe-server
    state: latest

- name: Ensure absence of per-file configurations configured via nrpe_local.cfg
  file:
    path: '{{ item }}'
    state: absent
  with_items:
   - /etc/nagios/nrpe.d/connection_timeout
   - /etc/nagios/nrpe.d/command_timeout
   - /etc/nagios/nrpe.d/allowed_hosts
   - /etc/nagios/nrpe.d/check_speedtest-cli-2
   - /etc/nagios/nrpe.d/check_speedtest-cli-10
   - /etc/nagios/nrpe.d/check_speedtest-cli-50
   - /etc/nagios/nrpe.d/check_speedtest-cli-100
   - /etc/nagios/nrpe.d/check_bandwidth
   - /etc/nagios/nrpe.d/
   - /etc/nagios/nrpe.d/check_load
   - /etc/nagios/nrpe.d/check_ram
   - /etc/nagios/nrpe.d/check_zombie_procs
   - /etc/nagios/nrpe.d/check_total_procs
   - /etc/nagios/nrpe.d/check_disk
   - /etc/nagios/nrpe.d/check_apt_succesful
   - /etc/nagios/nrpe.d/check_bird
   - /etc/nagios/nrpe.d/check_bird6
   - /etc/nagios/nrpe.d/check_bind
   - /etc/nagios/nrpe.d/check_collectd
   - /etc/nagios/nrpe.d/check_pyrespondd
   - /etc/nagios/nrpe.d/check_respondd
   - /etc/nagios/nrpe.d/check_tunneldigger
   - /etc/nagios/nrpe.d/check_dhcp-server
   - /etc/nagios/nrpe.d/check_isc-dhcp-server
   - /etc/nagios/nrpe.d/check_isc-dhcp-server-leases
   - /etc/nagios/nrpe.d/check_vnstat
   - /etc/nagios/nrpe.d/check-dhcp-client
   - /etc/nagios/nrpe.d/check-dns4-client
   - /etc/nagios/nrpe.d/check-dns6-client
   - /etc/nagios/nrpe.d/check-http4-client
   - /etc/nagios/nrpe.d/check-http6-client
   - /etc/nagios/nrpe.d/check-ping-v4
   - /etc/nagios/nrpe.d/check-ping-v6
   - /etc/nagios/nrpe.d/check_iproute
   - /etc/nagios/nrpe.d/check_iproute6
   - /etc/nagios/nrpe.d/check_bird_sessions
   - /etc/nagios/nrpe.d/check_bird6_sessions
   - /etc/nagios/nrpe.d/check_nginx
   - /etc/nagios/nrpe.d/check_raid
  notify: Reload nagios-nrpe-server

- name: Configure NRPE-Server
  template: "src=nrpe_local.cfg.j2 dest='/etc/nagios/nrpe_local.cfg' owner=root group=root"
  notify: Reload nagios-nrpe-server

- name: Install Nagios Plugins
  package:
    name: nagios-plugins-standard
    state: latest

- name: Install bc
  package:
    name: bc
    state: latest

- name: Install nagios-plugins-contrib
  package:
    name: nagios-plugins-contrib
    state: latest

- name: Install vnstat
  package:
    name: vnstat
    state: latest

- name: Install vnstati
  package:
    name: vnstati
    state: latest

- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Install RAM check
  copy: "src=check_ram dest='/usr/lib/nagios/plugins/check_ram' owner=root group=root mode=a+x"

- name: Install bandwith check
  copy: "src=check_bandwidth dest='/usr/lib/nagios/plugins/check_bandwidth' owner=root group=root mode=a+x"

- name: Install check_eth
  copy: "src=check_eth dest='/usr/lib/nagios/plugins/check_eth' owner=root group=root mode=a+x"

- name: Install check_systemd_service
  copy: "src=check_systemd_service dest='/usr/lib/nagios/plugins/check_systemd_service' owner=root group=root mode=a+x"

- name: Install check_tunneldigger
  copy: "src=check_tunneldigger dest='/usr/lib/nagios/plugins/check_tunneldigger' owner=root group=root mode=a+x"
  when: domaenenliste is defined and (tunneldigger is defined and tunneldigger.interface is defined)

- name: Install Speedtest
  package:
    name: speedtest-cli
    state: latest

- name: Install check_speedtest-cli plugin
  copy: src=check_speedtest-cli.sh dest=/usr/lib/nagios/plugins/check_speedtest-cli.sh owner=root group=root mode=a+x

- name: Install DHCP lease check
  package:
    name: dhcpd-pools
    state: present
  when: domaenenliste is defined and not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04')

- name: Install check_batip
  template: "src=check_batip.j2 dest='/usr/lib/nagios/plugins/check_batip' owner=root group=root mode=a+x"
  when: domaenenliste is defined

- name: Install check_batip6
  template: "src=check_batip6.j2 dest='/usr/lib/nagios/plugins/check_batip6' owner=root group=root mode=a+x"
  when: domaenenliste is defined

- name: Install check_iproute
  copy: "src=check_iproute dest='/usr/lib/nagios/plugins/check_iproute' owner=root group=root mode=a+x"
  when: domaenenliste is defined

- name: Install check_iproute6
  copy: "src=check_iproute6 dest='/usr/lib/nagios/plugins/check_iproute6' owner=root group=root mode=a+x"
  when: domaenenliste is defined

- name: Install check_bird_sessions
  copy: "src=check_bird_sessions dest='/usr/lib/nagios/plugins/check_bird_sessions' owner=root group=root mode=a+x"
  when: hostvars[inventory_hostname].bgp_router is not defined or not hostvars[inventory_hostname].bgp_router

- name: Install check_bird_sessions
  copy: "src=check_bird_sessions_router dest='/usr/lib/nagios/plugins/check_bird_sessions' owner=root group=root mode=a+x"
  when: hostvars[inventory_hostname].bgp_router is defined and hostvars[inventory_hostname].bgp_router

- name: Install check_bird6_sessions
  copy: "src=check_bird6_sessions dest='/usr/lib/nagios/plugins/check_bird6_sessions' owner=root group=root mode=a+x"
  when: hostvars[inventory_hostname].bgp_router is not defined or not hostvars[inventory_hostname].bgp_router

- name: Install check_bird6_sessions
  copy: "src=check_bird6_sessions_router dest='/usr/lib/nagios/plugins/check_bird6_sessions' owner=root group=root mode=a+x"
  when: hostvars[inventory_hostname].bgp_router is defined and hostvars[inventory_hostname].bgp_router

- name: Install sudo permissions
  template: "src=sudoers.j2 dest='/etc/sudoers.d/nrpe' owner=root group=root mode=440"

- name: enable NRPE-Server
  systemd:
    name: nagios-nrpe-server
    state: started
    enabled: yes
