---
- name: install packages to build gluon
  apt:
    name: ['vim', 'wget', 'rsync', 'git', 'subversion', 'python3', 'build-essential', 'gawk', 'unzip',
           'libncurses5-dev', 'zlib1g-dev', 'libssl-dev', 'wget', 'time', 'qemu-utils', 'python']
    update_cache: yes

- name: Creating build user with admin access
  user:
    name: "{{build_user}}"
    uid: 1000
    comment: "{{build_user_comment}}"
    password: "{{build_user_passwd}}"
    groups: sudo
    append: yes
    update_password: on_create
    shell: /bin/bash

- name: create .ssh
  file:
    path: /home/{{build_user}}/.ssh
    owner: "{{build_user}}"
    group: "{{build_user}}"
    state: directory
    mode: '0755'

- name: SSH-Schlüsseldatei generieren
  template:
    src: authorized_keys.j2
    dest: /home/{{build_user}}/.ssh/authorized_keys
    owner: "{{build_user}}"
    group: "{{build_user}}"
  when: administratorenteam is defined
